### PR TITLE
added cam interface to get data from Unreal with https://github.com/c…

### PR DESCRIPTION
**Pull request by Sanic**
…ode-iai/ROSIntegration

Hi!
This code adds a new ROSCamInterface to play with https://github.com/code-iai/ROSIntegrationVision .
You can use it in your AE by setting the camera_config_files to the config_unreal_rosintegration_vision.ini file.

### CODE REVIEW

**Comment by Sanic** [comment]
Thanks!

**Comment by bbferka** [comment]
@Sanic I think I rushed merging this. In it's current form it looks like the normal KinectBridge could be used, given a correct config file. I would also add the GT mask image to it as well, or at least have it optional.

**Comment by bbferka** [comment]
@Sanic PING! What do you think? I'm thinking of reverting this, because of the previously mentioned reason.

**Comment by Sanic** [comment]
Hi. I will test this and report back when my new box is ready to go.

**Comment by bbferka** [comment]
cool. I'm all for keeping it if we have extra functionalities that are not covered by the kinect bridge, such as the object maps or other meta data that is specific to the unreal integration;

**Pull request merged**
