### PR TITLE
Multi-modal Cluttered Scene Analysis in Knowledge Intensive Scenarios

### PR DESCRIPTION
**Pull request by anindex**
**Pull request summaries**
Implemented AEs:
- OverSegmentationAnnotator
- RotationalSymmetryAnnotator
- RotationalSymmetrySegmentation
- BilateralSymmetryAnnotator
- BilateralSymmetrySegmentation
- PointNormalNaNFilter
- SegmentationResultDisplayer

Pipelines:
- full_segmentation (combining rotational and bilateral symmetry segmentation on low noise clouds)
- object_segmentation (bilateral symmetry segmentation on raw clouds)

Datasets:
- 4 low noise clouds in author's dataset: www.umiacs.umd.edu/%7Eaecins/projects/symseg/dataset/CTD.tar.gz
- 2 raw clouds in TUW dataset: http://www.acin.tuwien.ac.at/?id=289
 
Documentation:
- In-code description
- Overview and usage in this [link](https://gist.github.com/anindex/ee4b32e73973ab24d3d7a17ab6486b9d)

Ongoing works:
- Combine rotational and bilateral symmetry segmentation in raw cloud scene (which would have better accuracy of segmentation)
- Unit testings that are compatible with RoboSherlock framework

### CODE REVIEW

**Comment by anindex** [comment]
I have successfully combined Rotational and Bilateral Symmetry Segmentation in both raw cloud and low-noise cloud pipeline. Check my new demo, you can see increment in accuracy of raw cloud segmentation pipeline.
https://www.youtube.com/watch?v=8tNZvQrNUj0

**Comment by anindex** [comment]
I have implemented unit-test that is able to call xml pipeline with one iteration and evaluates segmentation results by ground-truth tables.
To run unit test: 
`catkin_make run_tests_robosherlock`
Please note that you must call `roscore` first.
I am sorry that I forget to treat ground truth tables as binaries and the total lines increase so much. (they are actually text files)

**Comment by klokik** [comment]
Can you split it up? Like one feature - one PR, would be MUCH easier to read it.

**Comment by anindex** [comment]
Yeah sure, but some pull request features can not be tested until all parts are presented, because my system needs everything in one pipeline.
I will delete this pull request and make other PRs tomorrow.

**Pull request closed without merging**
