### PR TITLE
Update PointCloudCLusterExtractor.cpp for ROS noetic version

### PR DESCRIPTION
**Pull request by abmuslim**

### CODE REVIEW

**Comment by Sanic** [comment]
Hi @abmuslim !
Thanks for the PR.
I'm not sure if my notification settings are correct here. So it would be nice if you could ping/mention me when you've checked the comments on the review above. Thanks in advance.

**Review by abmuslim — COMMENTED** [review]
@Sanic

**Comment by Sanic** [comment]
Thanks. Can you please commit the requested changes to your noetic-dev branch on your fork?

**Comment by abmuslim** [comment]
I did it. please check.

**Comment by Sanic** [comment]
Hm, it looks like the requested changes still are not in this PR?

**Review by Sanic — CHANGES_REQUESTED** [review]

**Comment by Sanic** [comment]
Thanks! Looks good now 👍

**Pull request merged**
